package com.gjp.example.mbg.dao;

import com.gjp.example.mbg.model.MonCarInfo;
import com.gjp.example.mbg.model.MonCarInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGMonCarInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int countByExample(MonCarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int deleteByExample(MonCarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int insert(MonCarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int insertSelective(MonCarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    List<MonCarInfo> selectByExample(MonCarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    MonCarInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") MonCarInfo record, @Param("example") MonCarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByExample(@Param("record") MonCarInfo record, @Param("example") MonCarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByPrimaryKeySelective(MonCarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByPrimaryKey(MonCarInfo record);
}