package com.gjp.example.mbg.dao;

import com.gjp.example.mbg.model.MonCarBalanceInfo;
import com.gjp.example.mbg.model.MonCarBalanceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGMonCarBalanceInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int countByExample(MonCarBalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int deleteByExample(MonCarBalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int insert(MonCarBalanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int insertSelective(MonCarBalanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    List<MonCarBalanceInfo> selectByExample(MonCarBalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    MonCarBalanceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") MonCarBalanceInfo record, @Param("example") MonCarBalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByExample(@Param("record") MonCarBalanceInfo record, @Param("example") MonCarBalanceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByPrimaryKeySelective(MonCarBalanceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByPrimaryKey(MonCarBalanceInfo record);
}