package com.gjp.example.mbg.dao;

import com.gjp.example.mbg.model.MonCarTypeInfo;
import com.gjp.example.mbg.model.MonCarTypeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGMonCarTypeInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int countByExample(MonCarTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int deleteByExample(MonCarTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int insert(MonCarTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int insertSelective(MonCarTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    List<MonCarTypeInfo> selectByExample(MonCarTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    MonCarTypeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") MonCarTypeInfo record, @Param("example") MonCarTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByExample(@Param("record") MonCarTypeInfo record, @Param("example") MonCarTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByPrimaryKeySelective(MonCarTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByPrimaryKey(MonCarTypeInfo record);
}