package com.gjp.example.mbg.dao;

import com.gjp.example.mbg.model.MonDepartmentInfo;
import com.gjp.example.mbg.model.MonDepartmentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGMonDepartmentInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int countByExample(MonDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int deleteByExample(MonDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int insert(MonDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int insertSelective(MonDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    List<MonDepartmentInfo> selectByExampleWithBLOBs(MonDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    List<MonDepartmentInfo> selectByExample(MonDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    MonDepartmentInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") MonDepartmentInfo record, @Param("example") MonDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") MonDepartmentInfo record, @Param("example") MonDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int updateByExample(@Param("record") MonDepartmentInfo record, @Param("example") MonDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int updateByPrimaryKeySelective(MonDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(MonDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    int updateByPrimaryKey(MonDepartmentInfo record);
}