package com.gjp.example.mbg.dao;

import com.gjp.example.mbg.model.MonOperationInfo;
import com.gjp.example.mbg.model.MonOperationInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGMonOperationInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    int countByExample(MonOperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    int deleteByExample(MonOperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    int insert(MonOperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    int insertSelective(MonOperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    List<MonOperationInfo> selectByExample(MonOperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    MonOperationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") MonOperationInfo record, @Param("example") MonOperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    int updateByExample(@Param("record") MonOperationInfo record, @Param("example") MonOperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    int updateByPrimaryKeySelective(MonOperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    int updateByPrimaryKey(MonOperationInfo record);
}