package com.gjp.example.mbg.dao;

import com.gjp.example.mbg.model.MonCarDakaInfo;
import com.gjp.example.mbg.model.MonCarDakaInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGMonCarDakaInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int countByExample(MonCarDakaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int deleteByExample(MonCarDakaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int insert(MonCarDakaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int insertSelective(MonCarDakaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    List<MonCarDakaInfo> selectByExample(MonCarDakaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    MonCarDakaInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") MonCarDakaInfo record, @Param("example") MonCarDakaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByExample(@Param("record") MonCarDakaInfo record, @Param("example") MonCarDakaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByPrimaryKeySelective(MonCarDakaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    int updateByPrimaryKey(MonCarDakaInfo record);
}