package com.gjp.example.mbg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MonCarDakaInfoExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public MonCarDakaInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDriver_idIsNull() {
            addCriterion("driver_id is null");
            return (Criteria) this;
        }

        public Criteria andDriver_idIsNotNull() {
            addCriterion("driver_id is not null");
            return (Criteria) this;
        }

        public Criteria andDriver_idEqualTo(Integer value) {
            addCriterion("driver_id =", value, "driver_id");
            return (Criteria) this;
        }

        public Criteria andDriver_idNotEqualTo(Integer value) {
            addCriterion("driver_id <>", value, "driver_id");
            return (Criteria) this;
        }

        public Criteria andDriver_idGreaterThan(Integer value) {
            addCriterion("driver_id >", value, "driver_id");
            return (Criteria) this;
        }

        public Criteria andDriver_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("driver_id >=", value, "driver_id");
            return (Criteria) this;
        }

        public Criteria andDriver_idLessThan(Integer value) {
            addCriterion("driver_id <", value, "driver_id");
            return (Criteria) this;
        }

        public Criteria andDriver_idLessThanOrEqualTo(Integer value) {
            addCriterion("driver_id <=", value, "driver_id");
            return (Criteria) this;
        }

        public Criteria andDriver_idIn(List<Integer> values) {
            addCriterion("driver_id in", values, "driver_id");
            return (Criteria) this;
        }

        public Criteria andDriver_idNotIn(List<Integer> values) {
            addCriterion("driver_id not in", values, "driver_id");
            return (Criteria) this;
        }

        public Criteria andDriver_idBetween(Integer value1, Integer value2) {
            addCriterion("driver_id between", value1, value2, "driver_id");
            return (Criteria) this;
        }

        public Criteria andDriver_idNotBetween(Integer value1, Integer value2) {
            addCriterion("driver_id not between", value1, value2, "driver_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Integer value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Integer value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Integer value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Integer> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyIsNull() {
            addCriterion("driver_money is null");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyIsNotNull() {
            addCriterion("driver_money is not null");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyEqualTo(Double value) {
            addCriterion("driver_money =", value, "driver_money");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyNotEqualTo(Double value) {
            addCriterion("driver_money <>", value, "driver_money");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyGreaterThan(Double value) {
            addCriterion("driver_money >", value, "driver_money");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyGreaterThanOrEqualTo(Double value) {
            addCriterion("driver_money >=", value, "driver_money");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyLessThan(Double value) {
            addCriterion("driver_money <", value, "driver_money");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyLessThanOrEqualTo(Double value) {
            addCriterion("driver_money <=", value, "driver_money");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyIn(List<Double> values) {
            addCriterion("driver_money in", values, "driver_money");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyNotIn(List<Double> values) {
            addCriterion("driver_money not in", values, "driver_money");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyBetween(Double value1, Double value2) {
            addCriterion("driver_money between", value1, value2, "driver_money");
            return (Criteria) this;
        }

        public Criteria andDriver_moneyNotBetween(Double value1, Double value2) {
            addCriterion("driver_money not between", value1, value2, "driver_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyIsNull() {
            addCriterion("user_money is null");
            return (Criteria) this;
        }

        public Criteria andUser_moneyIsNotNull() {
            addCriterion("user_money is not null");
            return (Criteria) this;
        }

        public Criteria andUser_moneyEqualTo(Double value) {
            addCriterion("user_money =", value, "user_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyNotEqualTo(Double value) {
            addCriterion("user_money <>", value, "user_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyGreaterThan(Double value) {
            addCriterion("user_money >", value, "user_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyGreaterThanOrEqualTo(Double value) {
            addCriterion("user_money >=", value, "user_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyLessThan(Double value) {
            addCriterion("user_money <", value, "user_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyLessThanOrEqualTo(Double value) {
            addCriterion("user_money <=", value, "user_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyIn(List<Double> values) {
            addCriterion("user_money in", values, "user_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyNotIn(List<Double> values) {
            addCriterion("user_money not in", values, "user_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyBetween(Double value1, Double value2) {
            addCriterion("user_money between", value1, value2, "user_money");
            return (Criteria) this;
        }

        public Criteria andUser_moneyNotBetween(Double value1, Double value2) {
            addCriterion("user_money not between", value1, value2, "user_money");
            return (Criteria) this;
        }

        public Criteria andDpet_idIsNull() {
            addCriterion("dpet_id is null");
            return (Criteria) this;
        }

        public Criteria andDpet_idIsNotNull() {
            addCriterion("dpet_id is not null");
            return (Criteria) this;
        }

        public Criteria andDpet_idEqualTo(Integer value) {
            addCriterion("dpet_id =", value, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andDpet_idNotEqualTo(Integer value) {
            addCriterion("dpet_id <>", value, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andDpet_idGreaterThan(Integer value) {
            addCriterion("dpet_id >", value, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andDpet_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("dpet_id >=", value, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andDpet_idLessThan(Integer value) {
            addCriterion("dpet_id <", value, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andDpet_idLessThanOrEqualTo(Integer value) {
            addCriterion("dpet_id <=", value, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andDpet_idIn(List<Integer> values) {
            addCriterion("dpet_id in", values, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andDpet_idNotIn(List<Integer> values) {
            addCriterion("dpet_id not in", values, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andDpet_idBetween(Integer value1, Integer value2) {
            addCriterion("dpet_id between", value1, value2, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andDpet_idNotBetween(Integer value1, Integer value2) {
            addCriterion("dpet_id not between", value1, value2, "dpet_id");
            return (Criteria) this;
        }

        public Criteria andCar_idIsNull() {
            addCriterion("car_id is null");
            return (Criteria) this;
        }

        public Criteria andCar_idIsNotNull() {
            addCriterion("car_id is not null");
            return (Criteria) this;
        }

        public Criteria andCar_idEqualTo(Integer value) {
            addCriterion("car_id =", value, "car_id");
            return (Criteria) this;
        }

        public Criteria andCar_idNotEqualTo(Integer value) {
            addCriterion("car_id <>", value, "car_id");
            return (Criteria) this;
        }

        public Criteria andCar_idGreaterThan(Integer value) {
            addCriterion("car_id >", value, "car_id");
            return (Criteria) this;
        }

        public Criteria andCar_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_id >=", value, "car_id");
            return (Criteria) this;
        }

        public Criteria andCar_idLessThan(Integer value) {
            addCriterion("car_id <", value, "car_id");
            return (Criteria) this;
        }

        public Criteria andCar_idLessThanOrEqualTo(Integer value) {
            addCriterion("car_id <=", value, "car_id");
            return (Criteria) this;
        }

        public Criteria andCar_idIn(List<Integer> values) {
            addCriterion("car_id in", values, "car_id");
            return (Criteria) this;
        }

        public Criteria andCar_idNotIn(List<Integer> values) {
            addCriterion("car_id not in", values, "car_id");
            return (Criteria) this;
        }

        public Criteria andCar_idBetween(Integer value1, Integer value2) {
            addCriterion("car_id between", value1, value2, "car_id");
            return (Criteria) this;
        }

        public Criteria andCar_idNotBetween(Integer value1, Integer value2) {
            addCriterion("car_id not between", value1, value2, "car_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idIsNull() {
            addCriterion("daka_id is null");
            return (Criteria) this;
        }

        public Criteria andDaka_idIsNotNull() {
            addCriterion("daka_id is not null");
            return (Criteria) this;
        }

        public Criteria andDaka_idEqualTo(Integer value) {
            addCriterion("daka_id =", value, "daka_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idNotEqualTo(Integer value) {
            addCriterion("daka_id <>", value, "daka_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idGreaterThan(Integer value) {
            addCriterion("daka_id >", value, "daka_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("daka_id >=", value, "daka_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idLessThan(Integer value) {
            addCriterion("daka_id <", value, "daka_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idLessThanOrEqualTo(Integer value) {
            addCriterion("daka_id <=", value, "daka_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idIn(List<Integer> values) {
            addCriterion("daka_id in", values, "daka_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idNotIn(List<Integer> values) {
            addCriterion("daka_id not in", values, "daka_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idBetween(Integer value1, Integer value2) {
            addCriterion("daka_id between", value1, value2, "daka_id");
            return (Criteria) this;
        }

        public Criteria andDaka_idNotBetween(Integer value1, Integer value2) {
            addCriterion("daka_id not between", value1, value2, "daka_id");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeIsNull() {
            addCriterion("shoufei_time is null");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeIsNotNull() {
            addCriterion("shoufei_time is not null");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeEqualTo(Date value) {
            addCriterion("shoufei_time =", value, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeNotEqualTo(Date value) {
            addCriterion("shoufei_time <>", value, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeGreaterThan(Date value) {
            addCriterion("shoufei_time >", value, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("shoufei_time >=", value, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeLessThan(Date value) {
            addCriterion("shoufei_time <", value, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeLessThanOrEqualTo(Date value) {
            addCriterion("shoufei_time <=", value, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeIn(List<Date> values) {
            addCriterion("shoufei_time in", values, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeNotIn(List<Date> values) {
            addCriterion("shoufei_time not in", values, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeBetween(Date value1, Date value2) {
            addCriterion("shoufei_time between", value1, value2, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_timeNotBetween(Date value1, Date value2) {
            addCriterion("shoufei_time not between", value1, value2, "shoufei_time");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_IsNull() {
            addCriterion("shoufei_time_ is null");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_IsNotNull() {
            addCriterion("shoufei_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_EqualTo(Date value) {
            addCriterion("shoufei_time_ =", value, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_NotEqualTo(Date value) {
            addCriterion("shoufei_time_ <>", value, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_GreaterThan(Date value) {
            addCriterion("shoufei_time_ >", value, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_GreaterThanOrEqualTo(Date value) {
            addCriterion("shoufei_time_ >=", value, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_LessThan(Date value) {
            addCriterion("shoufei_time_ <", value, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_LessThanOrEqualTo(Date value) {
            addCriterion("shoufei_time_ <=", value, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_In(List<Date> values) {
            addCriterion("shoufei_time_ in", values, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_NotIn(List<Date> values) {
            addCriterion("shoufei_time_ not in", values, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_Between(Date value1, Date value2) {
            addCriterion("shoufei_time_ between", value1, value2, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andShoufei_time_NotBetween(Date value1, Date value2) {
            addCriterion("shoufei_time_ not between", value1, value2, "shoufei_time_");
            return (Criteria) this;
        }

        public Criteria andDanjia_idIsNull() {
            addCriterion("danjia_id is null");
            return (Criteria) this;
        }

        public Criteria andDanjia_idIsNotNull() {
            addCriterion("danjia_id is not null");
            return (Criteria) this;
        }

        public Criteria andDanjia_idEqualTo(Double value) {
            addCriterion("danjia_id =", value, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andDanjia_idNotEqualTo(Double value) {
            addCriterion("danjia_id <>", value, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andDanjia_idGreaterThan(Double value) {
            addCriterion("danjia_id >", value, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andDanjia_idGreaterThanOrEqualTo(Double value) {
            addCriterion("danjia_id >=", value, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andDanjia_idLessThan(Double value) {
            addCriterion("danjia_id <", value, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andDanjia_idLessThanOrEqualTo(Double value) {
            addCriterion("danjia_id <=", value, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andDanjia_idIn(List<Double> values) {
            addCriterion("danjia_id in", values, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andDanjia_idNotIn(List<Double> values) {
            addCriterion("danjia_id not in", values, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andDanjia_idBetween(Double value1, Double value2) {
            addCriterion("danjia_id between", value1, value2, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andDanjia_idNotBetween(Double value1, Double value2) {
            addCriterion("danjia_id not between", value1, value2, "danjia_id");
            return (Criteria) this;
        }

        public Criteria andLichengIsNull() {
            addCriterion("licheng is null");
            return (Criteria) this;
        }

        public Criteria andLichengIsNotNull() {
            addCriterion("licheng is not null");
            return (Criteria) this;
        }

        public Criteria andLichengEqualTo(Double value) {
            addCriterion("licheng =", value, "licheng");
            return (Criteria) this;
        }

        public Criteria andLichengNotEqualTo(Double value) {
            addCriterion("licheng <>", value, "licheng");
            return (Criteria) this;
        }

        public Criteria andLichengGreaterThan(Double value) {
            addCriterion("licheng >", value, "licheng");
            return (Criteria) this;
        }

        public Criteria andLichengGreaterThanOrEqualTo(Double value) {
            addCriterion("licheng >=", value, "licheng");
            return (Criteria) this;
        }

        public Criteria andLichengLessThan(Double value) {
            addCriterion("licheng <", value, "licheng");
            return (Criteria) this;
        }

        public Criteria andLichengLessThanOrEqualTo(Double value) {
            addCriterion("licheng <=", value, "licheng");
            return (Criteria) this;
        }

        public Criteria andLichengIn(List<Double> values) {
            addCriterion("licheng in", values, "licheng");
            return (Criteria) this;
        }

        public Criteria andLichengNotIn(List<Double> values) {
            addCriterion("licheng not in", values, "licheng");
            return (Criteria) this;
        }

        public Criteria andLichengBetween(Double value1, Double value2) {
            addCriterion("licheng between", value1, value2, "licheng");
            return (Criteria) this;
        }

        public Criteria andLichengNotBetween(Double value1, Double value2) {
            addCriterion("licheng not between", value1, value2, "licheng");
            return (Criteria) this;
        }

        public Criteria andWeizhangIsNull() {
            addCriterion("weizhang is null");
            return (Criteria) this;
        }

        public Criteria andWeizhangIsNotNull() {
            addCriterion("weizhang is not null");
            return (Criteria) this;
        }

        public Criteria andWeizhangEqualTo(String value) {
            addCriterion("weizhang =", value, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangNotEqualTo(String value) {
            addCriterion("weizhang <>", value, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangGreaterThan(String value) {
            addCriterion("weizhang >", value, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangGreaterThanOrEqualTo(String value) {
            addCriterion("weizhang >=", value, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangLessThan(String value) {
            addCriterion("weizhang <", value, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangLessThanOrEqualTo(String value) {
            addCriterion("weizhang <=", value, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangLike(String value) {
            addCriterion("weizhang like", value, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangNotLike(String value) {
            addCriterion("weizhang not like", value, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangIn(List<String> values) {
            addCriterion("weizhang in", values, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangNotIn(List<String> values) {
            addCriterion("weizhang not in", values, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangBetween(String value1, String value2) {
            addCriterion("weizhang between", value1, value2, "weizhang");
            return (Criteria) this;
        }

        public Criteria andWeizhangNotBetween(String value1, String value2) {
            addCriterion("weizhang not between", value1, value2, "weizhang");
            return (Criteria) this;
        }

        public Criteria andIs_flagIsNull() {
            addCriterion("is_flag is null");
            return (Criteria) this;
        }

        public Criteria andIs_flagIsNotNull() {
            addCriterion("is_flag is not null");
            return (Criteria) this;
        }

        public Criteria andIs_flagEqualTo(Integer value) {
            addCriterion("is_flag =", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagNotEqualTo(Integer value) {
            addCriterion("is_flag <>", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagGreaterThan(Integer value) {
            addCriterion("is_flag >", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_flag >=", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagLessThan(Integer value) {
            addCriterion("is_flag <", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagLessThanOrEqualTo(Integer value) {
            addCriterion("is_flag <=", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagIn(List<Integer> values) {
            addCriterion("is_flag in", values, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagNotIn(List<Integer> values) {
            addCriterion("is_flag not in", values, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagBetween(Integer value1, Integer value2) {
            addCriterion("is_flag between", value1, value2, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagNotBetween(Integer value1, Integer value2) {
            addCriterion("is_flag not between", value1, value2, "is_flag");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaIsNull() {
            addCriterion("car_address_daka is null");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaIsNotNull() {
            addCriterion("car_address_daka is not null");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaEqualTo(String value) {
            addCriterion("car_address_daka =", value, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaNotEqualTo(String value) {
            addCriterion("car_address_daka <>", value, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaGreaterThan(String value) {
            addCriterion("car_address_daka >", value, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaGreaterThanOrEqualTo(String value) {
            addCriterion("car_address_daka >=", value, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaLessThan(String value) {
            addCriterion("car_address_daka <", value, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaLessThanOrEqualTo(String value) {
            addCriterion("car_address_daka <=", value, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaLike(String value) {
            addCriterion("car_address_daka like", value, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaNotLike(String value) {
            addCriterion("car_address_daka not like", value, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaIn(List<String> values) {
            addCriterion("car_address_daka in", values, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaNotIn(List<String> values) {
            addCriterion("car_address_daka not in", values, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaBetween(String value1, String value2) {
            addCriterion("car_address_daka between", value1, value2, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_address_dakaNotBetween(String value1, String value2) {
            addCriterion("car_address_daka not between", value1, value2, "car_address_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaIsNull() {
            addCriterion("car_destination_daka is null");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaIsNotNull() {
            addCriterion("car_destination_daka is not null");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaEqualTo(String value) {
            addCriterion("car_destination_daka =", value, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaNotEqualTo(String value) {
            addCriterion("car_destination_daka <>", value, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaGreaterThan(String value) {
            addCriterion("car_destination_daka >", value, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaGreaterThanOrEqualTo(String value) {
            addCriterion("car_destination_daka >=", value, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaLessThan(String value) {
            addCriterion("car_destination_daka <", value, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaLessThanOrEqualTo(String value) {
            addCriterion("car_destination_daka <=", value, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaLike(String value) {
            addCriterion("car_destination_daka like", value, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaNotLike(String value) {
            addCriterion("car_destination_daka not like", value, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaIn(List<String> values) {
            addCriterion("car_destination_daka in", values, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaNotIn(List<String> values) {
            addCriterion("car_destination_daka not in", values, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaBetween(String value1, String value2) {
            addCriterion("car_destination_daka between", value1, value2, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_destination_dakaNotBetween(String value1, String value2) {
            addCriterion("car_destination_daka not between", value1, value2, "car_destination_daka");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoIsNull() {
            addCriterion("car_youhao is null");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoIsNotNull() {
            addCriterion("car_youhao is not null");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoEqualTo(Double value) {
            addCriterion("car_youhao =", value, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoNotEqualTo(Double value) {
            addCriterion("car_youhao <>", value, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoGreaterThan(Double value) {
            addCriterion("car_youhao >", value, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoGreaterThanOrEqualTo(Double value) {
            addCriterion("car_youhao >=", value, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoLessThan(Double value) {
            addCriterion("car_youhao <", value, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoLessThanOrEqualTo(Double value) {
            addCriterion("car_youhao <=", value, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoIn(List<Double> values) {
            addCriterion("car_youhao in", values, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoNotIn(List<Double> values) {
            addCriterion("car_youhao not in", values, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoBetween(Double value1, Double value2) {
            addCriterion("car_youhao between", value1, value2, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andCar_youhaoNotBetween(Double value1, Double value2) {
            addCriterion("car_youhao not between", value1, value2, "car_youhao");
            return (Criteria) this;
        }

        public Criteria andYong_che_renIsNull() {
            addCriterion("yong_che_ren is null");
            return (Criteria) this;
        }

        public Criteria andYong_che_renIsNotNull() {
            addCriterion("yong_che_ren is not null");
            return (Criteria) this;
        }

        public Criteria andYong_che_renEqualTo(String value) {
            addCriterion("yong_che_ren =", value, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renNotEqualTo(String value) {
            addCriterion("yong_che_ren <>", value, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renGreaterThan(String value) {
            addCriterion("yong_che_ren >", value, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renGreaterThanOrEqualTo(String value) {
            addCriterion("yong_che_ren >=", value, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renLessThan(String value) {
            addCriterion("yong_che_ren <", value, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renLessThanOrEqualTo(String value) {
            addCriterion("yong_che_ren <=", value, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renLike(String value) {
            addCriterion("yong_che_ren like", value, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renNotLike(String value) {
            addCriterion("yong_che_ren not like", value, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renIn(List<String> values) {
            addCriterion("yong_che_ren in", values, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renNotIn(List<String> values) {
            addCriterion("yong_che_ren not in", values, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renBetween(String value1, String value2) {
            addCriterion("yong_che_ren between", value1, value2, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andYong_che_renNotBetween(String value1, String value2) {
            addCriterion("yong_che_ren not between", value1, value2, "yong_che_ren");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idIsNull() {
            addCriterion("fy_apply_id is null");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idIsNotNull() {
            addCriterion("fy_apply_id is not null");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idEqualTo(Integer value) {
            addCriterion("fy_apply_id =", value, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idNotEqualTo(Integer value) {
            addCriterion("fy_apply_id <>", value, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idGreaterThan(Integer value) {
            addCriterion("fy_apply_id >", value, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("fy_apply_id >=", value, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idLessThan(Integer value) {
            addCriterion("fy_apply_id <", value, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idLessThanOrEqualTo(Integer value) {
            addCriterion("fy_apply_id <=", value, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idIn(List<Integer> values) {
            addCriterion("fy_apply_id in", values, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idNotIn(List<Integer> values) {
            addCriterion("fy_apply_id not in", values, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idBetween(Integer value1, Integer value2) {
            addCriterion("fy_apply_id between", value1, value2, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFy_apply_idNotBetween(Integer value1, Integer value2) {
            addCriterion("fy_apply_id not between", value1, value2, "fy_apply_id");
            return (Criteria) this;
        }

        public Criteria andFeiyongIsNull() {
            addCriterion("feiyong is null");
            return (Criteria) this;
        }

        public Criteria andFeiyongIsNotNull() {
            addCriterion("feiyong is not null");
            return (Criteria) this;
        }

        public Criteria andFeiyongEqualTo(Double value) {
            addCriterion("feiyong =", value, "feiyong");
            return (Criteria) this;
        }

        public Criteria andFeiyongNotEqualTo(Double value) {
            addCriterion("feiyong <>", value, "feiyong");
            return (Criteria) this;
        }

        public Criteria andFeiyongGreaterThan(Double value) {
            addCriterion("feiyong >", value, "feiyong");
            return (Criteria) this;
        }

        public Criteria andFeiyongGreaterThanOrEqualTo(Double value) {
            addCriterion("feiyong >=", value, "feiyong");
            return (Criteria) this;
        }

        public Criteria andFeiyongLessThan(Double value) {
            addCriterion("feiyong <", value, "feiyong");
            return (Criteria) this;
        }

        public Criteria andFeiyongLessThanOrEqualTo(Double value) {
            addCriterion("feiyong <=", value, "feiyong");
            return (Criteria) this;
        }

        public Criteria andFeiyongIn(List<Double> values) {
            addCriterion("feiyong in", values, "feiyong");
            return (Criteria) this;
        }

        public Criteria andFeiyongNotIn(List<Double> values) {
            addCriterion("feiyong not in", values, "feiyong");
            return (Criteria) this;
        }

        public Criteria andFeiyongBetween(Double value1, Double value2) {
            addCriterion("feiyong between", value1, value2, "feiyong");
            return (Criteria) this;
        }

        public Criteria andFeiyongNotBetween(Double value1, Double value2) {
            addCriterion("feiyong not between", value1, value2, "feiyong");
            return (Criteria) this;
        }

        public Criteria andXiaoshiIsNull() {
            addCriterion("xiaoshi is null");
            return (Criteria) this;
        }

        public Criteria andXiaoshiIsNotNull() {
            addCriterion("xiaoshi is not null");
            return (Criteria) this;
        }

        public Criteria andXiaoshiEqualTo(Double value) {
            addCriterion("xiaoshi =", value, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andXiaoshiNotEqualTo(Double value) {
            addCriterion("xiaoshi <>", value, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andXiaoshiGreaterThan(Double value) {
            addCriterion("xiaoshi >", value, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andXiaoshiGreaterThanOrEqualTo(Double value) {
            addCriterion("xiaoshi >=", value, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andXiaoshiLessThan(Double value) {
            addCriterion("xiaoshi <", value, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andXiaoshiLessThanOrEqualTo(Double value) {
            addCriterion("xiaoshi <=", value, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andXiaoshiIn(List<Double> values) {
            addCriterion("xiaoshi in", values, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andXiaoshiNotIn(List<Double> values) {
            addCriterion("xiaoshi not in", values, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andXiaoshiBetween(Double value1, Double value2) {
            addCriterion("xiaoshi between", value1, value2, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andXiaoshiNotBetween(Double value1, Double value2) {
            addCriterion("xiaoshi not between", value1, value2, "xiaoshi");
            return (Criteria) this;
        }

        public Criteria andJichuIsNull() {
            addCriterion("jichu is null");
            return (Criteria) this;
        }

        public Criteria andJichuIsNotNull() {
            addCriterion("jichu is not null");
            return (Criteria) this;
        }

        public Criteria andJichuEqualTo(Double value) {
            addCriterion("jichu =", value, "jichu");
            return (Criteria) this;
        }

        public Criteria andJichuNotEqualTo(Double value) {
            addCriterion("jichu <>", value, "jichu");
            return (Criteria) this;
        }

        public Criteria andJichuGreaterThan(Double value) {
            addCriterion("jichu >", value, "jichu");
            return (Criteria) this;
        }

        public Criteria andJichuGreaterThanOrEqualTo(Double value) {
            addCriterion("jichu >=", value, "jichu");
            return (Criteria) this;
        }

        public Criteria andJichuLessThan(Double value) {
            addCriterion("jichu <", value, "jichu");
            return (Criteria) this;
        }

        public Criteria andJichuLessThanOrEqualTo(Double value) {
            addCriterion("jichu <=", value, "jichu");
            return (Criteria) this;
        }

        public Criteria andJichuIn(List<Double> values) {
            addCriterion("jichu in", values, "jichu");
            return (Criteria) this;
        }

        public Criteria andJichuNotIn(List<Double> values) {
            addCriterion("jichu not in", values, "jichu");
            return (Criteria) this;
        }

        public Criteria andJichuBetween(Double value1, Double value2) {
            addCriterion("jichu between", value1, value2, "jichu");
            return (Criteria) this;
        }

        public Criteria andJichuNotBetween(Double value1, Double value2) {
            addCriterion("jichu not between", value1, value2, "jichu");
            return (Criteria) this;
        }

        public Criteria andFujiaIsNull() {
            addCriterion("fujia is null");
            return (Criteria) this;
        }

        public Criteria andFujiaIsNotNull() {
            addCriterion("fujia is not null");
            return (Criteria) this;
        }

        public Criteria andFujiaEqualTo(Double value) {
            addCriterion("fujia =", value, "fujia");
            return (Criteria) this;
        }

        public Criteria andFujiaNotEqualTo(Double value) {
            addCriterion("fujia <>", value, "fujia");
            return (Criteria) this;
        }

        public Criteria andFujiaGreaterThan(Double value) {
            addCriterion("fujia >", value, "fujia");
            return (Criteria) this;
        }

        public Criteria andFujiaGreaterThanOrEqualTo(Double value) {
            addCriterion("fujia >=", value, "fujia");
            return (Criteria) this;
        }

        public Criteria andFujiaLessThan(Double value) {
            addCriterion("fujia <", value, "fujia");
            return (Criteria) this;
        }

        public Criteria andFujiaLessThanOrEqualTo(Double value) {
            addCriterion("fujia <=", value, "fujia");
            return (Criteria) this;
        }

        public Criteria andFujiaIn(List<Double> values) {
            addCriterion("fujia in", values, "fujia");
            return (Criteria) this;
        }

        public Criteria andFujiaNotIn(List<Double> values) {
            addCriterion("fujia not in", values, "fujia");
            return (Criteria) this;
        }

        public Criteria andFujiaBetween(Double value1, Double value2) {
            addCriterion("fujia between", value1, value2, "fujia");
            return (Criteria) this;
        }

        public Criteria andFujiaNotBetween(Double value1, Double value2) {
            addCriterion("fujia not between", value1, value2, "fujia");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmIsNull() {
            addCriterion("xingshi_km is null");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmIsNotNull() {
            addCriterion("xingshi_km is not null");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmEqualTo(Double value) {
            addCriterion("xingshi_km =", value, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmNotEqualTo(Double value) {
            addCriterion("xingshi_km <>", value, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmGreaterThan(Double value) {
            addCriterion("xingshi_km >", value, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmGreaterThanOrEqualTo(Double value) {
            addCriterion("xingshi_km >=", value, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmLessThan(Double value) {
            addCriterion("xingshi_km <", value, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmLessThanOrEqualTo(Double value) {
            addCriterion("xingshi_km <=", value, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmIn(List<Double> values) {
            addCriterion("xingshi_km in", values, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmNotIn(List<Double> values) {
            addCriterion("xingshi_km not in", values, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmBetween(Double value1, Double value2) {
            addCriterion("xingshi_km between", value1, value2, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andXingshi_kmNotBetween(Double value1, Double value2) {
            addCriterion("xingshi_km not between", value1, value2, "xingshi_km");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiIsNull() {
            addCriterion("feiyong_zhiyi is null");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiIsNotNull() {
            addCriterion("feiyong_zhiyi is not null");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiEqualTo(String value) {
            addCriterion("feiyong_zhiyi =", value, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiNotEqualTo(String value) {
            addCriterion("feiyong_zhiyi <>", value, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiGreaterThan(String value) {
            addCriterion("feiyong_zhiyi >", value, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiGreaterThanOrEqualTo(String value) {
            addCriterion("feiyong_zhiyi >=", value, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiLessThan(String value) {
            addCriterion("feiyong_zhiyi <", value, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiLessThanOrEqualTo(String value) {
            addCriterion("feiyong_zhiyi <=", value, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiLike(String value) {
            addCriterion("feiyong_zhiyi like", value, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiNotLike(String value) {
            addCriterion("feiyong_zhiyi not like", value, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiIn(List<String> values) {
            addCriterion("feiyong_zhiyi in", values, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiNotIn(List<String> values) {
            addCriterion("feiyong_zhiyi not in", values, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiBetween(String value1, String value2) {
            addCriterion("feiyong_zhiyi between", value1, value2, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andFeiyong_zhiyiNotBetween(String value1, String value2) {
            addCriterion("feiyong_zhiyi not between", value1, value2, "feiyong_zhiyi");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesIsNull() {
            addCriterion("yong_che_times is null");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesIsNotNull() {
            addCriterion("yong_che_times is not null");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesEqualTo(String value) {
            addCriterion("yong_che_times =", value, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesNotEqualTo(String value) {
            addCriterion("yong_che_times <>", value, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesGreaterThan(String value) {
            addCriterion("yong_che_times >", value, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesGreaterThanOrEqualTo(String value) {
            addCriterion("yong_che_times >=", value, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesLessThan(String value) {
            addCriterion("yong_che_times <", value, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesLessThanOrEqualTo(String value) {
            addCriterion("yong_che_times <=", value, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesLike(String value) {
            addCriterion("yong_che_times like", value, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesNotLike(String value) {
            addCriterion("yong_che_times not like", value, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesIn(List<String> values) {
            addCriterion("yong_che_times in", values, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesNotIn(List<String> values) {
            addCriterion("yong_che_times not in", values, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesBetween(String value1, String value2) {
            addCriterion("yong_che_times between", value1, value2, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andYong_che_timesNotBetween(String value1, String value2) {
            addCriterion("yong_che_times not between", value1, value2, "yong_che_times");
            return (Criteria) this;
        }

        public Criteria andCity_codeIsNull() {
            addCriterion("city_code is null");
            return (Criteria) this;
        }

        public Criteria andCity_codeIsNotNull() {
            addCriterion("city_code is not null");
            return (Criteria) this;
        }

        public Criteria andCity_codeEqualTo(String value) {
            addCriterion("city_code =", value, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeNotEqualTo(String value) {
            addCriterion("city_code <>", value, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeGreaterThan(String value) {
            addCriterion("city_code >", value, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeGreaterThanOrEqualTo(String value) {
            addCriterion("city_code >=", value, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeLessThan(String value) {
            addCriterion("city_code <", value, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeLessThanOrEqualTo(String value) {
            addCriterion("city_code <=", value, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeLike(String value) {
            addCriterion("city_code like", value, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeNotLike(String value) {
            addCriterion("city_code not like", value, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeIn(List<String> values) {
            addCriterion("city_code in", values, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeNotIn(List<String> values) {
            addCriterion("city_code not in", values, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeBetween(String value1, String value2) {
            addCriterion("city_code between", value1, value2, "city_code");
            return (Criteria) this;
        }

        public Criteria andCity_codeNotBetween(String value1, String value2) {
            addCriterion("city_code not between", value1, value2, "city_code");
            return (Criteria) this;
        }

        public Criteria andOld_idIsNull() {
            addCriterion("old_id is null");
            return (Criteria) this;
        }

        public Criteria andOld_idIsNotNull() {
            addCriterion("old_id is not null");
            return (Criteria) this;
        }

        public Criteria andOld_idEqualTo(Long value) {
            addCriterion("old_id =", value, "old_id");
            return (Criteria) this;
        }

        public Criteria andOld_idNotEqualTo(Long value) {
            addCriterion("old_id <>", value, "old_id");
            return (Criteria) this;
        }

        public Criteria andOld_idGreaterThan(Long value) {
            addCriterion("old_id >", value, "old_id");
            return (Criteria) this;
        }

        public Criteria andOld_idGreaterThanOrEqualTo(Long value) {
            addCriterion("old_id >=", value, "old_id");
            return (Criteria) this;
        }

        public Criteria andOld_idLessThan(Long value) {
            addCriterion("old_id <", value, "old_id");
            return (Criteria) this;
        }

        public Criteria andOld_idLessThanOrEqualTo(Long value) {
            addCriterion("old_id <=", value, "old_id");
            return (Criteria) this;
        }

        public Criteria andOld_idIn(List<Long> values) {
            addCriterion("old_id in", values, "old_id");
            return (Criteria) this;
        }

        public Criteria andOld_idNotIn(List<Long> values) {
            addCriterion("old_id not in", values, "old_id");
            return (Criteria) this;
        }

        public Criteria andOld_idBetween(Long value1, Long value2) {
            addCriterion("old_id between", value1, value2, "old_id");
            return (Criteria) this;
        }

        public Criteria andOld_idNotBetween(Long value1, Long value2) {
            addCriterion("old_id not between", value1, value2, "old_id");
            return (Criteria) this;
        }

        public Criteria andSyna_timeIsNull() {
            addCriterion("syna_time is null");
            return (Criteria) this;
        }

        public Criteria andSyna_timeIsNotNull() {
            addCriterion("syna_time is not null");
            return (Criteria) this;
        }

        public Criteria andSyna_timeEqualTo(Date value) {
            addCriterion("syna_time =", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeNotEqualTo(Date value) {
            addCriterion("syna_time <>", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeGreaterThan(Date value) {
            addCriterion("syna_time >", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("syna_time >=", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeLessThan(Date value) {
            addCriterion("syna_time <", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeLessThanOrEqualTo(Date value) {
            addCriterion("syna_time <=", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeIn(List<Date> values) {
            addCriterion("syna_time in", values, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeNotIn(List<Date> values) {
            addCriterion("syna_time not in", values, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeBetween(Date value1, Date value2) {
            addCriterion("syna_time between", value1, value2, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeNotBetween(Date value1, Date value2) {
            addCriterion("syna_time not between", value1, value2, "syna_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 29 16:11:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}