package com.gjp.example.mbg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MonDepartmentInfoExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public MonDepartmentInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDept_nameIsNull() {
            addCriterion("dept_name is null");
            return (Criteria) this;
        }

        public Criteria andDept_nameIsNotNull() {
            addCriterion("dept_name is not null");
            return (Criteria) this;
        }

        public Criteria andDept_nameEqualTo(String value) {
            addCriterion("dept_name =", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameNotEqualTo(String value) {
            addCriterion("dept_name <>", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameGreaterThan(String value) {
            addCriterion("dept_name >", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameGreaterThanOrEqualTo(String value) {
            addCriterion("dept_name >=", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameLessThan(String value) {
            addCriterion("dept_name <", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameLessThanOrEqualTo(String value) {
            addCriterion("dept_name <=", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameLike(String value) {
            addCriterion("dept_name like", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameNotLike(String value) {
            addCriterion("dept_name not like", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameIn(List<String> values) {
            addCriterion("dept_name in", values, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameNotIn(List<String> values) {
            addCriterion("dept_name not in", values, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameBetween(String value1, String value2) {
            addCriterion("dept_name between", value1, value2, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameNotBetween(String value1, String value2) {
            addCriterion("dept_name not between", value1, value2, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_typeIsNull() {
            addCriterion("dept_type is null");
            return (Criteria) this;
        }

        public Criteria andDept_typeIsNotNull() {
            addCriterion("dept_type is not null");
            return (Criteria) this;
        }

        public Criteria andDept_typeEqualTo(Integer value) {
            addCriterion("dept_type =", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeNotEqualTo(Integer value) {
            addCriterion("dept_type <>", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeGreaterThan(Integer value) {
            addCriterion("dept_type >", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("dept_type >=", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeLessThan(Integer value) {
            addCriterion("dept_type <", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeLessThanOrEqualTo(Integer value) {
            addCriterion("dept_type <=", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeIn(List<Integer> values) {
            addCriterion("dept_type in", values, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeNotIn(List<Integer> values) {
            addCriterion("dept_type not in", values, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeBetween(Integer value1, Integer value2) {
            addCriterion("dept_type between", value1, value2, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("dept_type not between", value1, value2, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_super_idIsNull() {
            addCriterion("dept_super_id is null");
            return (Criteria) this;
        }

        public Criteria andDept_super_idIsNotNull() {
            addCriterion("dept_super_id is not null");
            return (Criteria) this;
        }

        public Criteria andDept_super_idEqualTo(Integer value) {
            addCriterion("dept_super_id =", value, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_super_idNotEqualTo(Integer value) {
            addCriterion("dept_super_id <>", value, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_super_idGreaterThan(Integer value) {
            addCriterion("dept_super_id >", value, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_super_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("dept_super_id >=", value, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_super_idLessThan(Integer value) {
            addCriterion("dept_super_id <", value, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_super_idLessThanOrEqualTo(Integer value) {
            addCriterion("dept_super_id <=", value, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_super_idIn(List<Integer> values) {
            addCriterion("dept_super_id in", values, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_super_idNotIn(List<Integer> values) {
            addCriterion("dept_super_id not in", values, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_super_idBetween(Integer value1, Integer value2) {
            addCriterion("dept_super_id between", value1, value2, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_super_idNotBetween(Integer value1, Integer value2) {
            addCriterion("dept_super_id not between", value1, value2, "dept_super_id");
            return (Criteria) this;
        }

        public Criteria andDept_descIsNull() {
            addCriterion("dept_desc is null");
            return (Criteria) this;
        }

        public Criteria andDept_descIsNotNull() {
            addCriterion("dept_desc is not null");
            return (Criteria) this;
        }

        public Criteria andDept_descEqualTo(String value) {
            addCriterion("dept_desc =", value, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descNotEqualTo(String value) {
            addCriterion("dept_desc <>", value, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descGreaterThan(String value) {
            addCriterion("dept_desc >", value, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descGreaterThanOrEqualTo(String value) {
            addCriterion("dept_desc >=", value, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descLessThan(String value) {
            addCriterion("dept_desc <", value, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descLessThanOrEqualTo(String value) {
            addCriterion("dept_desc <=", value, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descLike(String value) {
            addCriterion("dept_desc like", value, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descNotLike(String value) {
            addCriterion("dept_desc not like", value, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descIn(List<String> values) {
            addCriterion("dept_desc in", values, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descNotIn(List<String> values) {
            addCriterion("dept_desc not in", values, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descBetween(String value1, String value2) {
            addCriterion("dept_desc between", value1, value2, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_descNotBetween(String value1, String value2) {
            addCriterion("dept_desc not between", value1, value2, "dept_desc");
            return (Criteria) this;
        }

        public Criteria andDept_latIsNull() {
            addCriterion("dept_lat is null");
            return (Criteria) this;
        }

        public Criteria andDept_latIsNotNull() {
            addCriterion("dept_lat is not null");
            return (Criteria) this;
        }

        public Criteria andDept_latEqualTo(String value) {
            addCriterion("dept_lat =", value, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latNotEqualTo(String value) {
            addCriterion("dept_lat <>", value, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latGreaterThan(String value) {
            addCriterion("dept_lat >", value, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latGreaterThanOrEqualTo(String value) {
            addCriterion("dept_lat >=", value, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latLessThan(String value) {
            addCriterion("dept_lat <", value, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latLessThanOrEqualTo(String value) {
            addCriterion("dept_lat <=", value, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latLike(String value) {
            addCriterion("dept_lat like", value, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latNotLike(String value) {
            addCriterion("dept_lat not like", value, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latIn(List<String> values) {
            addCriterion("dept_lat in", values, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latNotIn(List<String> values) {
            addCriterion("dept_lat not in", values, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latBetween(String value1, String value2) {
            addCriterion("dept_lat between", value1, value2, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_latNotBetween(String value1, String value2) {
            addCriterion("dept_lat not between", value1, value2, "dept_lat");
            return (Criteria) this;
        }

        public Criteria andDept_lonIsNull() {
            addCriterion("dept_lon is null");
            return (Criteria) this;
        }

        public Criteria andDept_lonIsNotNull() {
            addCriterion("dept_lon is not null");
            return (Criteria) this;
        }

        public Criteria andDept_lonEqualTo(String value) {
            addCriterion("dept_lon =", value, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonNotEqualTo(String value) {
            addCriterion("dept_lon <>", value, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonGreaterThan(String value) {
            addCriterion("dept_lon >", value, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonGreaterThanOrEqualTo(String value) {
            addCriterion("dept_lon >=", value, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonLessThan(String value) {
            addCriterion("dept_lon <", value, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonLessThanOrEqualTo(String value) {
            addCriterion("dept_lon <=", value, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonLike(String value) {
            addCriterion("dept_lon like", value, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonNotLike(String value) {
            addCriterion("dept_lon not like", value, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonIn(List<String> values) {
            addCriterion("dept_lon in", values, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonNotIn(List<String> values) {
            addCriterion("dept_lon not in", values, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonBetween(String value1, String value2) {
            addCriterion("dept_lon between", value1, value2, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_lonNotBetween(String value1, String value2) {
            addCriterion("dept_lon not between", value1, value2, "dept_lon");
            return (Criteria) this;
        }

        public Criteria andDept_adressIsNull() {
            addCriterion("dept_adress is null");
            return (Criteria) this;
        }

        public Criteria andDept_adressIsNotNull() {
            addCriterion("dept_adress is not null");
            return (Criteria) this;
        }

        public Criteria andDept_adressEqualTo(String value) {
            addCriterion("dept_adress =", value, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressNotEqualTo(String value) {
            addCriterion("dept_adress <>", value, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressGreaterThan(String value) {
            addCriterion("dept_adress >", value, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressGreaterThanOrEqualTo(String value) {
            addCriterion("dept_adress >=", value, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressLessThan(String value) {
            addCriterion("dept_adress <", value, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressLessThanOrEqualTo(String value) {
            addCriterion("dept_adress <=", value, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressLike(String value) {
            addCriterion("dept_adress like", value, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressNotLike(String value) {
            addCriterion("dept_adress not like", value, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressIn(List<String> values) {
            addCriterion("dept_adress in", values, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressNotIn(List<String> values) {
            addCriterion("dept_adress not in", values, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressBetween(String value1, String value2) {
            addCriterion("dept_adress between", value1, value2, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andDept_adressNotBetween(String value1, String value2) {
            addCriterion("dept_adress not between", value1, value2, "dept_adress");
            return (Criteria) this;
        }

        public Criteria andIs_flagIsNull() {
            addCriterion("is_flag is null");
            return (Criteria) this;
        }

        public Criteria andIs_flagIsNotNull() {
            addCriterion("is_flag is not null");
            return (Criteria) this;
        }

        public Criteria andIs_flagEqualTo(Integer value) {
            addCriterion("is_flag =", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagNotEqualTo(Integer value) {
            addCriterion("is_flag <>", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagGreaterThan(Integer value) {
            addCriterion("is_flag >", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_flag >=", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagLessThan(Integer value) {
            addCriterion("is_flag <", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagLessThanOrEqualTo(Integer value) {
            addCriterion("is_flag <=", value, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagIn(List<Integer> values) {
            addCriterion("is_flag in", values, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagNotIn(List<Integer> values) {
            addCriterion("is_flag not in", values, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagBetween(Integer value1, Integer value2) {
            addCriterion("is_flag between", value1, value2, "is_flag");
            return (Criteria) this;
        }

        public Criteria andIs_flagNotBetween(Integer value1, Integer value2) {
            addCriterion("is_flag not between", value1, value2, "is_flag");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkIsNull() {
            addCriterion("dapt_remark is null");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkIsNotNull() {
            addCriterion("dapt_remark is not null");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkEqualTo(String value) {
            addCriterion("dapt_remark =", value, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkNotEqualTo(String value) {
            addCriterion("dapt_remark <>", value, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkGreaterThan(String value) {
            addCriterion("dapt_remark >", value, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkGreaterThanOrEqualTo(String value) {
            addCriterion("dapt_remark >=", value, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkLessThan(String value) {
            addCriterion("dapt_remark <", value, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkLessThanOrEqualTo(String value) {
            addCriterion("dapt_remark <=", value, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkLike(String value) {
            addCriterion("dapt_remark like", value, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkNotLike(String value) {
            addCriterion("dapt_remark not like", value, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkIn(List<String> values) {
            addCriterion("dapt_remark in", values, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkNotIn(List<String> values) {
            addCriterion("dapt_remark not in", values, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkBetween(String value1, String value2) {
            addCriterion("dapt_remark between", value1, value2, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andDapt_remarkNotBetween(String value1, String value2) {
            addCriterion("dapt_remark not between", value1, value2, "dapt_remark");
            return (Criteria) this;
        }

        public Criteria andGs_idIsNull() {
            addCriterion("gs_id is null");
            return (Criteria) this;
        }

        public Criteria andGs_idIsNotNull() {
            addCriterion("gs_id is not null");
            return (Criteria) this;
        }

        public Criteria andGs_idEqualTo(Integer value) {
            addCriterion("gs_id =", value, "gs_id");
            return (Criteria) this;
        }

        public Criteria andGs_idNotEqualTo(Integer value) {
            addCriterion("gs_id <>", value, "gs_id");
            return (Criteria) this;
        }

        public Criteria andGs_idGreaterThan(Integer value) {
            addCriterion("gs_id >", value, "gs_id");
            return (Criteria) this;
        }

        public Criteria andGs_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("gs_id >=", value, "gs_id");
            return (Criteria) this;
        }

        public Criteria andGs_idLessThan(Integer value) {
            addCriterion("gs_id <", value, "gs_id");
            return (Criteria) this;
        }

        public Criteria andGs_idLessThanOrEqualTo(Integer value) {
            addCriterion("gs_id <=", value, "gs_id");
            return (Criteria) this;
        }

        public Criteria andGs_idIn(List<Integer> values) {
            addCriterion("gs_id in", values, "gs_id");
            return (Criteria) this;
        }

        public Criteria andGs_idNotIn(List<Integer> values) {
            addCriterion("gs_id not in", values, "gs_id");
            return (Criteria) this;
        }

        public Criteria andGs_idBetween(Integer value1, Integer value2) {
            addCriterion("gs_id between", value1, value2, "gs_id");
            return (Criteria) this;
        }

        public Criteria andGs_idNotBetween(Integer value1, Integer value2) {
            addCriterion("gs_id not between", value1, value2, "gs_id");
            return (Criteria) this;
        }

        public Criteria andPt_idIsNull() {
            addCriterion("pt_id is null");
            return (Criteria) this;
        }

        public Criteria andPt_idIsNotNull() {
            addCriterion("pt_id is not null");
            return (Criteria) this;
        }

        public Criteria andPt_idEqualTo(Integer value) {
            addCriterion("pt_id =", value, "pt_id");
            return (Criteria) this;
        }

        public Criteria andPt_idNotEqualTo(Integer value) {
            addCriterion("pt_id <>", value, "pt_id");
            return (Criteria) this;
        }

        public Criteria andPt_idGreaterThan(Integer value) {
            addCriterion("pt_id >", value, "pt_id");
            return (Criteria) this;
        }

        public Criteria andPt_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("pt_id >=", value, "pt_id");
            return (Criteria) this;
        }

        public Criteria andPt_idLessThan(Integer value) {
            addCriterion("pt_id <", value, "pt_id");
            return (Criteria) this;
        }

        public Criteria andPt_idLessThanOrEqualTo(Integer value) {
            addCriterion("pt_id <=", value, "pt_id");
            return (Criteria) this;
        }

        public Criteria andPt_idIn(List<Integer> values) {
            addCriterion("pt_id in", values, "pt_id");
            return (Criteria) this;
        }

        public Criteria andPt_idNotIn(List<Integer> values) {
            addCriterion("pt_id not in", values, "pt_id");
            return (Criteria) this;
        }

        public Criteria andPt_idBetween(Integer value1, Integer value2) {
            addCriterion("pt_id between", value1, value2, "pt_id");
            return (Criteria) this;
        }

        public Criteria andPt_idNotBetween(Integer value1, Integer value2) {
            addCriterion("pt_id not between", value1, value2, "pt_id");
            return (Criteria) this;
        }

        public Criteria andFw_typeIsNull() {
            addCriterion("fw_type is null");
            return (Criteria) this;
        }

        public Criteria andFw_typeIsNotNull() {
            addCriterion("fw_type is not null");
            return (Criteria) this;
        }

        public Criteria andFw_typeEqualTo(Integer value) {
            addCriterion("fw_type =", value, "fw_type");
            return (Criteria) this;
        }

        public Criteria andFw_typeNotEqualTo(Integer value) {
            addCriterion("fw_type <>", value, "fw_type");
            return (Criteria) this;
        }

        public Criteria andFw_typeGreaterThan(Integer value) {
            addCriterion("fw_type >", value, "fw_type");
            return (Criteria) this;
        }

        public Criteria andFw_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fw_type >=", value, "fw_type");
            return (Criteria) this;
        }

        public Criteria andFw_typeLessThan(Integer value) {
            addCriterion("fw_type <", value, "fw_type");
            return (Criteria) this;
        }

        public Criteria andFw_typeLessThanOrEqualTo(Integer value) {
            addCriterion("fw_type <=", value, "fw_type");
            return (Criteria) this;
        }

        public Criteria andFw_typeIn(List<Integer> values) {
            addCriterion("fw_type in", values, "fw_type");
            return (Criteria) this;
        }

        public Criteria andFw_typeNotIn(List<Integer> values) {
            addCriterion("fw_type not in", values, "fw_type");
            return (Criteria) this;
        }

        public Criteria andFw_typeBetween(Integer value1, Integer value2) {
            addCriterion("fw_type between", value1, value2, "fw_type");
            return (Criteria) this;
        }

        public Criteria andFw_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("fw_type not between", value1, value2, "fw_type");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsIsNull() {
            addCriterion("dept_super_ids is null");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsIsNotNull() {
            addCriterion("dept_super_ids is not null");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsEqualTo(String value) {
            addCriterion("dept_super_ids =", value, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsNotEqualTo(String value) {
            addCriterion("dept_super_ids <>", value, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsGreaterThan(String value) {
            addCriterion("dept_super_ids >", value, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsGreaterThanOrEqualTo(String value) {
            addCriterion("dept_super_ids >=", value, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsLessThan(String value) {
            addCriterion("dept_super_ids <", value, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsLessThanOrEqualTo(String value) {
            addCriterion("dept_super_ids <=", value, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsLike(String value) {
            addCriterion("dept_super_ids like", value, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsNotLike(String value) {
            addCriterion("dept_super_ids not like", value, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsIn(List<String> values) {
            addCriterion("dept_super_ids in", values, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsNotIn(List<String> values) {
            addCriterion("dept_super_ids not in", values, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsBetween(String value1, String value2) {
            addCriterion("dept_super_ids between", value1, value2, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andDept_super_idsNotBetween(String value1, String value2) {
            addCriterion("dept_super_ids not between", value1, value2, "dept_super_ids");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("color is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("color is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("color =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("color <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("color >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("color >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("color <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("color <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("color like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("color not like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<String> values) {
            addCriterion("color in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<String> values) {
            addCriterion("color not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("color between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("color not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andQy_idIsNull() {
            addCriterion("qy_id is null");
            return (Criteria) this;
        }

        public Criteria andQy_idIsNotNull() {
            addCriterion("qy_id is not null");
            return (Criteria) this;
        }

        public Criteria andQy_idEqualTo(Integer value) {
            addCriterion("qy_id =", value, "qy_id");
            return (Criteria) this;
        }

        public Criteria andQy_idNotEqualTo(Integer value) {
            addCriterion("qy_id <>", value, "qy_id");
            return (Criteria) this;
        }

        public Criteria andQy_idGreaterThan(Integer value) {
            addCriterion("qy_id >", value, "qy_id");
            return (Criteria) this;
        }

        public Criteria andQy_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("qy_id >=", value, "qy_id");
            return (Criteria) this;
        }

        public Criteria andQy_idLessThan(Integer value) {
            addCriterion("qy_id <", value, "qy_id");
            return (Criteria) this;
        }

        public Criteria andQy_idLessThanOrEqualTo(Integer value) {
            addCriterion("qy_id <=", value, "qy_id");
            return (Criteria) this;
        }

        public Criteria andQy_idIn(List<Integer> values) {
            addCriterion("qy_id in", values, "qy_id");
            return (Criteria) this;
        }

        public Criteria andQy_idNotIn(List<Integer> values) {
            addCriterion("qy_id not in", values, "qy_id");
            return (Criteria) this;
        }

        public Criteria andQy_idBetween(Integer value1, Integer value2) {
            addCriterion("qy_id between", value1, value2, "qy_id");
            return (Criteria) this;
        }

        public Criteria andQy_idNotBetween(Integer value1, Integer value2) {
            addCriterion("qy_id not between", value1, value2, "qy_id");
            return (Criteria) this;
        }

        public Criteria andOrgcodingIsNull() {
            addCriterion("orgcoding is null");
            return (Criteria) this;
        }

        public Criteria andOrgcodingIsNotNull() {
            addCriterion("orgcoding is not null");
            return (Criteria) this;
        }

        public Criteria andOrgcodingEqualTo(String value) {
            addCriterion("orgcoding =", value, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingNotEqualTo(String value) {
            addCriterion("orgcoding <>", value, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingGreaterThan(String value) {
            addCriterion("orgcoding >", value, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingGreaterThanOrEqualTo(String value) {
            addCriterion("orgcoding >=", value, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingLessThan(String value) {
            addCriterion("orgcoding <", value, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingLessThanOrEqualTo(String value) {
            addCriterion("orgcoding <=", value, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingLike(String value) {
            addCriterion("orgcoding like", value, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingNotLike(String value) {
            addCriterion("orgcoding not like", value, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingIn(List<String> values) {
            addCriterion("orgcoding in", values, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingNotIn(List<String> values) {
            addCriterion("orgcoding not in", values, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingBetween(String value1, String value2) {
            addCriterion("orgcoding between", value1, value2, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgcodingNotBetween(String value1, String value2) {
            addCriterion("orgcoding not between", value1, value2, "orgcoding");
            return (Criteria) this;
        }

        public Criteria andOrgallnameIsNull() {
            addCriterion("orgallname is null");
            return (Criteria) this;
        }

        public Criteria andOrgallnameIsNotNull() {
            addCriterion("orgallname is not null");
            return (Criteria) this;
        }

        public Criteria andOrgallnameEqualTo(String value) {
            addCriterion("orgallname =", value, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameNotEqualTo(String value) {
            addCriterion("orgallname <>", value, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameGreaterThan(String value) {
            addCriterion("orgallname >", value, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameGreaterThanOrEqualTo(String value) {
            addCriterion("orgallname >=", value, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameLessThan(String value) {
            addCriterion("orgallname <", value, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameLessThanOrEqualTo(String value) {
            addCriterion("orgallname <=", value, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameLike(String value) {
            addCriterion("orgallname like", value, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameNotLike(String value) {
            addCriterion("orgallname not like", value, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameIn(List<String> values) {
            addCriterion("orgallname in", values, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameNotIn(List<String> values) {
            addCriterion("orgallname not in", values, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameBetween(String value1, String value2) {
            addCriterion("orgallname between", value1, value2, "orgallname");
            return (Criteria) this;
        }

        public Criteria andOrgallnameNotBetween(String value1, String value2) {
            addCriterion("orgallname not between", value1, value2, "orgallname");
            return (Criteria) this;
        }

        public Criteria andDept_flagIsNull() {
            addCriterion("dept_flag is null");
            return (Criteria) this;
        }

        public Criteria andDept_flagIsNotNull() {
            addCriterion("dept_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDept_flagEqualTo(Integer value) {
            addCriterion("dept_flag =", value, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_flagNotEqualTo(Integer value) {
            addCriterion("dept_flag <>", value, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_flagGreaterThan(Integer value) {
            addCriterion("dept_flag >", value, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_flagGreaterThanOrEqualTo(Integer value) {
            addCriterion("dept_flag >=", value, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_flagLessThan(Integer value) {
            addCriterion("dept_flag <", value, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_flagLessThanOrEqualTo(Integer value) {
            addCriterion("dept_flag <=", value, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_flagIn(List<Integer> values) {
            addCriterion("dept_flag in", values, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_flagNotIn(List<Integer> values) {
            addCriterion("dept_flag not in", values, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_flagBetween(Integer value1, Integer value2) {
            addCriterion("dept_flag between", value1, value2, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_flagNotBetween(Integer value1, Integer value2) {
            addCriterion("dept_flag not between", value1, value2, "dept_flag");
            return (Criteria) this;
        }

        public Criteria andDept_numberIsNull() {
            addCriterion("dept_number is null");
            return (Criteria) this;
        }

        public Criteria andDept_numberIsNotNull() {
            addCriterion("dept_number is not null");
            return (Criteria) this;
        }

        public Criteria andDept_numberEqualTo(String value) {
            addCriterion("dept_number =", value, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberNotEqualTo(String value) {
            addCriterion("dept_number <>", value, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberGreaterThan(String value) {
            addCriterion("dept_number >", value, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberGreaterThanOrEqualTo(String value) {
            addCriterion("dept_number >=", value, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberLessThan(String value) {
            addCriterion("dept_number <", value, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberLessThanOrEqualTo(String value) {
            addCriterion("dept_number <=", value, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberLike(String value) {
            addCriterion("dept_number like", value, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberNotLike(String value) {
            addCriterion("dept_number not like", value, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberIn(List<String> values) {
            addCriterion("dept_number in", values, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberNotIn(List<String> values) {
            addCriterion("dept_number not in", values, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberBetween(String value1, String value2) {
            addCriterion("dept_number between", value1, value2, "dept_number");
            return (Criteria) this;
        }

        public Criteria andDept_numberNotBetween(String value1, String value2) {
            addCriterion("dept_number not between", value1, value2, "dept_number");
            return (Criteria) this;
        }

        public Criteria andSyna_timeIsNull() {
            addCriterion("syna_time is null");
            return (Criteria) this;
        }

        public Criteria andSyna_timeIsNotNull() {
            addCriterion("syna_time is not null");
            return (Criteria) this;
        }

        public Criteria andSyna_timeEqualTo(Date value) {
            addCriterion("syna_time =", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeNotEqualTo(Date value) {
            addCriterion("syna_time <>", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeGreaterThan(Date value) {
            addCriterion("syna_time >", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("syna_time >=", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeLessThan(Date value) {
            addCriterion("syna_time <", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeLessThanOrEqualTo(Date value) {
            addCriterion("syna_time <=", value, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeIn(List<Date> values) {
            addCriterion("syna_time in", values, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeNotIn(List<Date> values) {
            addCriterion("syna_time not in", values, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeBetween(Date value1, Date value2) {
            addCriterion("syna_time between", value1, value2, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_timeNotBetween(Date value1, Date value2) {
            addCriterion("syna_time not between", value1, value2, "syna_time");
            return (Criteria) this;
        }

        public Criteria andSyna_flagIsNull() {
            addCriterion("syna_flag is null");
            return (Criteria) this;
        }

        public Criteria andSyna_flagIsNotNull() {
            addCriterion("syna_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSyna_flagEqualTo(String value) {
            addCriterion("syna_flag =", value, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagNotEqualTo(String value) {
            addCriterion("syna_flag <>", value, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagGreaterThan(String value) {
            addCriterion("syna_flag >", value, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagGreaterThanOrEqualTo(String value) {
            addCriterion("syna_flag >=", value, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagLessThan(String value) {
            addCriterion("syna_flag <", value, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagLessThanOrEqualTo(String value) {
            addCriterion("syna_flag <=", value, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagLike(String value) {
            addCriterion("syna_flag like", value, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagNotLike(String value) {
            addCriterion("syna_flag not like", value, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagIn(List<String> values) {
            addCriterion("syna_flag in", values, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagNotIn(List<String> values) {
            addCriterion("syna_flag not in", values, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagBetween(String value1, String value2) {
            addCriterion("syna_flag between", value1, value2, "syna_flag");
            return (Criteria) this;
        }

        public Criteria andSyna_flagNotBetween(String value1, String value2) {
            addCriterion("syna_flag not between", value1, value2, "syna_flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mon_department_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 30 14:42:16 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}