package com.gjp.example.mbg.model;

public class MonUserInfoWithBLOBs extends MonUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.zygzjl
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String zygzjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.jtzycy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String jtzycy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.zygzjl
     *
     * @return the value of mon_user_info.zygzjl
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getZygzjl() {
        return zygzjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.zygzjl
     *
     * @param zygzjl the value for mon_user_info.zygzjl
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setZygzjl(String zygzjl) {
        this.zygzjl = zygzjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.jtzycy
     *
     * @return the value of mon_user_info.jtzycy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getJtzycy() {
        return jtzycy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.jtzycy
     *
     * @param jtzycy the value for mon_user_info.jtzycy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setJtzycy(String jtzycy) {
        this.jtzycy = jtzycy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_user_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", zygzjl=").append(zygzjl);
        sb.append(", jtzycy=").append(jtzycy);
        sb.append("]");
        return sb.toString();
    }
}